#!/usr/bin/env bash
#
# Interactive setup for seam-server.yaml.
# Generates a JWT secret, prompts for data directory and LLM provider,
# and writes a ready-to-use config file.

set -euo pipefail

CONFIG="seam-server.yaml"
EXAMPLE="seam-server.yaml.example"

# -- helpers ------------------------------------------------------------------

info()  { printf "\033[1;34m==>\033[0m %s\n" "$1"; }
ok()    { printf "\033[1;32m==>\033[0m %s\n" "$1"; }
warn()  { printf "\033[1;33m==>\033[0m %s\n" "$1"; }
ask()   { printf "\033[1;37m  > \033[0m%s " "$1"; }

# -- preflight ----------------------------------------------------------------

if [ ! -f "$EXAMPLE" ]; then
    warn "Cannot find $EXAMPLE. Run this from the repository root."
    exit 1
fi

if [ -f "$CONFIG" ]; then
    ask "$CONFIG already exists. Overwrite? [y/N]"
    read -r overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        info "Keeping existing config. Nothing to do."
        exit 0
    fi
    echo
fi

info "Setting up Seam"
echo

# -- JWT secret ---------------------------------------------------------------

info "Generating JWT secret..."
JWT_SECRET=$(openssl rand -hex 32)
ok "JWT secret generated (64 hex chars)"
echo

# -- data directory -----------------------------------------------------------

DEFAULT_DATA_DIR="./data"
ask "Data directory (notes, databases, templates) [$DEFAULT_DATA_DIR]:"
read -r DATA_DIR
DATA_DIR="${DATA_DIR:-$DEFAULT_DATA_DIR}"

# Expand ~ if the user typed it
DATA_DIR="${DATA_DIR/#\~/$HOME}"

echo

# -- LLM provider -------------------------------------------------------------

info "LLM provider for chat completions (embeddings always run on local Ollama)"
echo "  1) ollama    -- fully local, no API costs"
echo "  2) openai    -- GPT-4o, or any OpenAI-compatible API"
echo "  3) anthropic -- Claude"
echo
ask "Provider [1]:"
read -r PROVIDER_CHOICE
echo

case "${PROVIDER_CHOICE:-1}" in
    1|ollama)    LLM_PROVIDER="ollama" ;;
    2|openai)    LLM_PROVIDER="openai" ;;
    3|anthropic) LLM_PROVIDER="anthropic" ;;
    *)
        warn "Unknown choice '$PROVIDER_CHOICE', defaulting to ollama"
        LLM_PROVIDER="ollama"
        ;;
esac

OPENAI_API_KEY=""
OPENAI_BASE_URL=""
ANTHROPIC_API_KEY=""

if [ "$LLM_PROVIDER" = "openai" ]; then
    ask "OpenAI API key (or set SEAM_OPENAI_API_KEY env var later):"
    read -r OPENAI_API_KEY
    echo

    ask "Custom base URL? (leave blank for api.openai.com, or enter for Azure/Together/Groq):"
    read -r OPENAI_BASE_URL
    echo
elif [ "$LLM_PROVIDER" = "anthropic" ]; then
    ask "Anthropic API key (or set SEAM_ANTHROPIC_API_KEY env var later):"
    read -r ANTHROPIC_API_KEY
    echo
fi

# -- Ollama URL ---------------------------------------------------------------

DEFAULT_OLLAMA_URL="http://localhost:11434"
ask "Ollama URL [$DEFAULT_OLLAMA_URL]:"
read -r OLLAMA_URL
OLLAMA_URL="${OLLAMA_URL:-$DEFAULT_OLLAMA_URL}"
echo

# -- ChromaDB URL -------------------------------------------------------------

DEFAULT_CHROMA_URL="http://localhost:8000"
ask "ChromaDB URL (blank to disable semantic search) [$DEFAULT_CHROMA_URL]:"
read -r CHROMA_URL
CHROMA_URL="${CHROMA_URL:-$DEFAULT_CHROMA_URL}"
echo

# -- listen address -----------------------------------------------------------

DEFAULT_LISTEN=":8080"
ask "Listen address [$DEFAULT_LISTEN]:"
read -r LISTEN
LISTEN="${LISTEN:-$DEFAULT_LISTEN}"
echo

# -- write config -------------------------------------------------------------

cat > "$CONFIG" << EOF
# Seam server configuration
# Generated by: make init

listen: "${LISTEN}"
data_dir: "${DATA_DIR}"
jwt_secret: "${JWT_SECRET}"
ollama_base_url: "${OLLAMA_URL}"
chromadb_url: "${CHROMA_URL}"

models:
  embeddings: "qwen3-embedding:8b"
  background: "qwen3:32b"
  chat: "qwen3:32b"

llm:
  provider: "${LLM_PROVIDER}"
  openai:
    api_key: "${OPENAI_API_KEY}"
    base_url: "${OPENAI_BASE_URL}"
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"

whisper:
  model_path: ""
  binary_path: "whisper-cli"

auth:
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"
  bcrypt_cost: 12

ai:
  queue_workers: 1
  embedding_timeout: "60s"
  chat_timeout: "5m"

userdb:
  eviction_timeout: "30m"

watcher:
  debounce_interval: "200ms"
EOF

ok "Wrote $CONFIG"
echo

# -- summary ------------------------------------------------------------------

info "Configuration summary:"
echo "  Listen:       ${LISTEN}"
echo "  Data dir:     ${DATA_DIR}"
echo "  LLM provider: ${LLM_PROVIDER}"
echo "  Ollama:       ${OLLAMA_URL}"
echo "  ChromaDB:     ${CHROMA_URL}"
echo

# -- next steps ---------------------------------------------------------------

info "Next steps:"
echo "  make build              # build server + TUI"
echo "  make run                # start the server"
echo

if [ "$LLM_PROVIDER" = "ollama" ]; then
    info "Pull the default models:"
    echo "  ollama pull qwen3:32b"
    echo "  ollama pull qwen3-embedding:8b"
    echo
fi

if [ -n "$OPENAI_API_KEY" ] || [ -n "$ANTHROPIC_API_KEY" ]; then
    warn "API key written to $CONFIG. Make sure this file is in .gitignore."
fi
